groups:
- name: /prometheus-data/alert.rules
  rules:
  - alert: InstanceDown
    expr: up < 1
    for: 30s
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 30s.'
      summary: Instance {{ $labels.instance }} down
